#\u7981\u7528thymeleaf\u7684\u7F13\u5B58
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
    show-sql: true
logging:
  level:
    root: warn
    com.hui: info
  file:
    name: log/blog.log
server:
  port: 8081